# -*- coding: utf-8 -*-
"""Movie Theatre Booking System .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YXy-p-MFWNI208ip3VQZ6cTYftLfILg

#Movie Theatre Booking System
"""

total_seats = 350
tickets_sold = 0
total_bookings = 0
rejected_bookings = 0

while True:
  tickets = int(input("Enter the number of tickets(0 to exit): "))
  if tickets == 0:
    break

  #Check ticket limit
  if tickets < 1 or tickets > 15:
    print("BOOKING REJECTED - Invalict ticket count")
    rejected_bookings += 1
    continue
    valid = True

    #check seat availability
    if tickets > total_seats:
     print("BOOKING REJECTED - Insufficient seat")
     rejected_bookings += 1
     continue

     valid = True

      #check age
    for i in range(tickets):
       age = int(input(f"Enter age of ticket holder {i:1}:"))
       if age < 12:
          valid= False
          if not valid:
            print("BOOKING REJECTED - Children not allowed")
            rejected_bookings += 1
            break

        #Booking confirmed
       print(f"BOOKING CONFIRMED - {tickets} tickets sold")
       total_bookings += 1
       tickets_sold += tickets
       total_bookings += tickets

       if total_seats == 0:
        print("THEATER FULL")
        break

        #Final
        print("\nFinal Report")
        print("Total Bookings:", total_bookings)
        print("Tickets Sold:", tickets_sold)
        print("Rejected Bookings:", rejected_bookings)
        print("Remaining Seats:", total_seats)