# -*- coding: utf-8 -*-
"""python_basics_<Kusuma>.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CipqV5nJFura491K9BcV4eiupNTIWueF

#Task 1: Variables and Data Types
"""

name = "Rama"
age = 25
height = 1.83
is_student = True
print (name, age, height, is_student)

"""#Task 2: String Formatting"""

print (f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

"""#Task 3: Arithmetic Operations"""

Age_in_months = age*12
Age_in_days =age*365
The_remainder_when_age_is_divided_by_7 = age%7
Age_raised_to_the_power_of_2 = age**2

print("Age_in_months:", Age_in_months)
print("Age_in_days:", Age_in_days)
print("The_remainder_when_age_is_divided_by_7:", The_remainder_when_age_is_divided_by_7)
print("Age_raised_to_the_power_of_2:", Age_raised_to_the_power_of_2)